name: hipstur # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Store all your music, audiobooks, and ebooks completely free!
description: |
  Want to own your music but tired of transferring files around and running out of storage space. Stream and download the songs and playlists you own easily.

grade: stable #devel # must be 'stable' to release into candidate/stable channels
confinement: strict #devmode # use 'strict' once you have the right plugs and slots


        #armv7l
        #s390x



parts:
  hipstur:
   #override-build: bash ./stage.sh
    plugin: dump
    source: .
    #override-prime: snapcraftctl prime && chmod +x /stage.sh && ./stage.sh
    override-pull: |
      snapcraftctl pull
      echo "TEST HERE $(arch)"
      case "$(arch)" in
        "x86_64")
          mv hipstur.x86_64 hipstur
          ;;
        "ppc64le")
          mv hipstur.ppc64le hipstur
          ;;
        "aarch64")
          echo "HERE ARCH $(arch)"
          ;;
        *)
          echo "HERE OTHER ARCH $(arch)"
          exit 1
          ;;
      esac
      ls
      echo "OVERRIDE DONE"
    stage-packages:
      # Accelerated Renderer support for libSDL2
      - libglu1-mesa
      - libgl1-mesa-dri
      # libSDL2
      #- libsdl2-dev
      # libpulse
      - libpulse0
      - libpulse-dev
      - libgtk2.0-0


#- qtwayland5


#parts:
#  hipstur:
#    plugin: dump
#    source: release


#architectures:
#  build-on: amd64
#  build-on: arm64
#  build-on: armhf

#architectures:
#  - amd64
#  - arm64
#  - armhf


#  architectures:
#  - build-on: [amd64]
#    build-for: [amd64]
#  - build-on: [amd64, arm64]
#    build-for: [arm64]


apps:
  hipstur:
    #command: ./launch.sh
    command: hipstur

    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    plugs:
      - home
      - opengl
      - pulseaudio
      - audio-playback
      - x11
      - desktop
      - desktop-legacy
      - joystick
      - unity7
      - network
      - removable-media
      - wayland
      - gsettings
      - screen-inhibit-control

#      - uinput



# - input #doesnt exist
# - system-files:
#    read:
#      - /dev/input/
#    write:
#      - /dev/input/

#env:
#  plugin: copy
#    files:
#      hipstur: usr/bin/hipstur


icon: hipstur.png
